items_show:
    path:    /show/{iditems}
    defaults: { _controller: "ItemsBundle:Items:show" }
    methods:  GET

items_new:
    path:     /new
    defaults: { _controller: "ItemsBundle:Items:new" }
    methods:  [GET, POST]

items_edit:
    path:     /edit/{iditems}
    defaults: { _controller: "ItemsBundle:Items:edit" }
    methods:  [GET, POST]

items_delete:
    path:     /delete/{iditems}
    defaults: { _controller: "ItemsBundle:Items:delete" }
    methods:  DELETE
