<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ttoxz9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ttoxz9/appProdProjectContainer.php') {
    touch(__DIR__.'/Container0ttoxz9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container0ttoxz9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container0ttoxz9\appProdProjectContainer(array(
    'container.build_hash' => '0ttoxz9',
    'container.build_id' => '05520740',
    'container.build_time' => 1543282990,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0ttoxz9');
