<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWgufeef\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWgufeef/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWgufeef.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWgufeef\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWgufeef\appProdProjectContainer(array(
    'container.build_hash' => 'Wgufeef',
    'container.build_id' => 'dd293204',
    'container.build_time' => 1543462002,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWgufeef');
