Profil_troc:
    path:     /profil
    defaults: { _controller: TrocBundle:Profile:index }
troc_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
read_commentaire:
    path:     /readc
    defaults: { _controller: TrocBundle:Commentaire:readc }
create_commentaire:
    path:     /createc
    defaults: { _controller: TrocBundle:Commentaire:createc }
delete_commentaire:
    path:     /delete/{idCommentaire}
    defaults: { _controller: TrocBundle:Commentaire:delete }
update_commentaire:
    path:     /update/{idCommentaire}
    defaults: { _controller: TrocBundle:Commentaire:update }
top_commentaire:
    path:     /topCommentaire
    defaults: { _controller: TrocBundle:Commentaire:topCommentaire }
read_signaler:
    path:     /reads
    defaults: { _controller: TrocBundle:Signaler:reads }
signaler_commentaire:
    path:     /creates/{idCommentaire}
    defaults: { _controller: TrocBundle:Signaler:creates }
delete_signaler:
    path:     /deletes/{idSignale}
    defaults: { _controller: TrocBundle:Signaler:deletes }



read:
    path:     /read/{id}
    defaults: { _controller: TrocBundle:Annonce:read }
index:
    path:     /index
    defaults: { _controller: TrocBundle:Commentaire:index }
troc_signin:
    path:     /signin
    defaults: { _controller: TrocBundle:Signin:index }

rec_ajout:
    path:     /Recnew
    defaults: { _controller: TrocBundle:Reclamation:new }
rec_edit:
    path:     /edit/{idRec}
    defaults: { _controller: TrocBundle:Reclamation:edit }
rec_delete:
    path:     /delete/{idRec}
    defaults: { _controller: TrocBundle:Reclamation:delete }
feed_ajout:
    path:     /feedNew
    defaults: { _controller: TrocBundle:Feedback:new }
feed_aff:
    path:     /feedShow
    defaults: { _controller: TrocBundle:Feedback:show }
feed_like:
    path:     /feedlike
    defaults: { _controller: TrocBundle:Feedback:addLike }
opinon_ajout:
    path:     /ajouto
    defaults: { _controller: TrocBundle:Opinion:new }
opinion_aff:
    path:     /ajoutof
    defaults: { _controller: TrocBundle:Opinion:show }
opinion_success:
    path:     /success
    defaults: { _controller: TrocBundle:Opinion:Success }
feedback_Count:
    path:     /feedCount/{id}
    defaults: { _controller: TrocBundle:Feedback:CountLike }
signin:
    path:     /signin
    defaults: { _controller: TrocBundle:Connexion:signin }
signup:
    path:     /signup
    defaults: { _controller: TrocBundle:Connexion:signup }
page:
    path:     /single
    defaults: { _controller: TrocBundle:Default:page }

AlloCoursierCancel:
    path:     /AlloCoursierCancel/{idalloservice}
    defaults: { _controller: TrocBundle:Allocoursier:AlloCoursierCancel }
AlloCoursierCreate:
    path:     /ajoutAlloCoursier
    defaults: { _controller: TrocBundle:Allocoursier:AlloCoursierCreate }
AlloCoursierRead:
    path:     /listAlloCoursier
    defaults: { _controller: TrocBundle:Allocoursier:AlloCoursierRead }
AlloCoursierDelete:
    path:     /AlloCoursierDelete/{idalloservice}
    defaults: { _controller: TrocBundle:Allocoursier:AlloCoursierDelete }
AlloCoursierUpdate:
    path:     /AlloCoursierUpdate/{idalloservice}
    defaults: { _controller: TrocBundle:Allocoursier:AlloCoursierUpdate}
LivraisonCreate:
    path:     /LivraisonCreate
    defaults: { _controller: TrocBundle:Livraison:LivraisonCreate }
LivraisonRead:
    path:     /listLivraison
    defaults: { _controller: TrocBundle:Livraison:LivraisonRead }
LivraisonDelete:
    path:     /LivraisonDelete/{idLivraison}
    defaults: { _controller: TrocBundle:Livraison:LivraisonDelete }
LivraisonUpdate:
    path:     /LivraisonUpdate/{idLivraison}
    defaults: { _controller: TrocBundle:Livraison:LivraisonUpdate}
LivraisonValide:
    path:     /ValiderLivraison/{idLivraison}
    defaults: { _controller: TrocBundle:Livraison:ValiderLivraison}
LivraisonCancel:
    path:     /LivraisonCancel/{idLivraison}
    defaults: { _controller: TrocBundle:Livraison:CancelLivraison }
LivraisonParDate:
    path:     /LivraisonParDate/{dateEnregistrement}
    defaults: { _controller: TrocBundle:Livraison:LivraisonParDate }
showcoursier:
    path:     /listCoursier
    defaults: { _controller: TrocBundle:Livraison:showcoursier }
livraisondate:
    path:     /livraisondate
    defaults: { _controller: TrocBundle:Livraison:livraisondate }
comment:
    path:     /test
    defaults: { _controller: TrocBundle:Livraison:idComment }
rec_admin:
    path:     /admin
    defaults: { _controller: TrocBundle:Reclamation:index }

rec_addM:
    path:     /addRM
    defaults: { _controller: TrocBundle:Reclamation:newM }
rec_showM:
    path:     /showRM
    defaults: { _controller: TrocBundle:Reclamation:showM }
rec_deteleM:
    path:     /deleteRM
    defaults: { _controller: TrocBundle:Reclamation:deleteM }
rec_editM:
    path:     /editRM
    defaults: { _controller: TrocBundle:Reclamation:editM }

Loginm:
    path:     /loginm
    defaults: { _controller: TrocBundle:Reclamation:loginm }

ajout_commentaire:
    path:     /newc
    defaults: { _controller: TrocBundle:Commentaire:newc }
afficher_commentaire:
    path:     /showc
    defaults: { _controller: TrocBundle:Commentaire:showc }
supprimer_commentaire:
    path:     /deletec/{idCommentaire}
    defaults: { _controller: TrocBundle:Commentaire:deletec }
modifier_commentaire:
    path:     /editc/{idCommentaire}
    defaults: { _controller: TrocBundle:Commentaire:editc }
Loginm:
    path:     /loginmm
    defaults: { _controller: TrocBundle:Commentaire:loginm }
afficher_par_annonce:
    path:     /readByAnnonceM
    defaults: { _controller: TrocBundle:Commentaire:readByAnnonceM }
affichageClientAlMobile:
    path:     /listedelivered/{id}
    defaults: { _controller: TrocBundle:Livraison:listDelivClientAl}
affichageClientAlMobile2:
    path:     /listeCanceled/{id}
    defaults: { _controller: TrocBundle:Livraison:listCanClientAl}
affichageClientAlMobile3:
    path:     /listeToDeliv/{id}
    defaults: { _controller: TrocBundle:Livraison:listToDelivClientAl}

affichageClientlivAlMobile:
    path:     /listedeliveredLiv/{id}
    defaults: { _controller: TrocBundle:Livraison:listDelivClientLiv}
affichageClientlivMobile2:
    path:     /listeCanceledLiv/{id}
    defaults: { _controller: TrocBundle:Livraison:listCanClientLiv}
affichageClientlivMobile3:
    path:     /listeToDelivLiv/{id}
    defaults: { _controller: TrocBundle:Livraison:listToDelivClientLiv}

cacelMobileCleint:
    path:     /CancelClient/{id}
    defaults: { _controller: TrocBundle:Livraison:CancelClient}
AdresseMobileCleint:
    path:     /AdresseClient/{id}/{adresse}
    defaults: { _controller: TrocBundle:Livraison:ChangeClientAddress}
