troc_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
read_commentaire:
    path:     /readc
    defaults: { _controller: TrocBundle:Commentaire:readc }
create_commentaire:
    path:     /createc
    defaults: { _controller: TrocBundle:Commentaire:createc }
read:
    path:     /read/{id}
    defaults: { _controller: TrocBundle:Annonce:read }
index:
    path:     /index
    defaults: { _controller: TrocBundle:Commentaire:index }
troc_signin:
    path:     /signin
    defaults: { _controller: TrocBundle:Signin:index }

rec_ajout:
    path:     /Recnew
    defaults: { _controller: TrocBundle:Reclamation:new }

feed_ajout:
    path:     /feedNew
    defaults: { _controller: TrocBundle:Feedback:new }
feed_aff:
    path:     /feedShow
    defaults: { _controller: TrocBundle:Feedback:show }
feed_like:
    path:     /feedlike
    defaults: { _controller: TrocBundle:Feedback:addLike }
opinon_ajout:
    path:     /ajouto
    defaults: { _controller: TrocBundle:Opinion:new }
opinion_aff:
    path:     /opinonShow
    defaults: { _controller: TrocBundle:Opinion:show }
opinion_success:
    path:     /success
    defaults: { _controller: TrocBundle:Opinion:Success }
feedback_Count:
    path:     /feedCount/{id}
    defaults: { _controller: TrocBundle:Feedback:CountLike }
signin:
    path:     /signin
    defaults: { _controller: TrocBundle:Connexion:signin }
signup:
    path:     /signup
    defaults: { _controller: TrocBundle:Connexion:signup }
page:
    path:     /single
    defaults: { _controller: TrocBundle:Default:page }

rec_admin:
    path:     /admin
    defaults: { _controller: TrocBundle:Reclamation:Reclamation }