troc_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

read_commentaire:
    path:     /readc
    defaults: { _controller: TrocBundle:Commentaire:readc }
create_commentaire:
    path:     /createc
    defaults: { _controller: TrocBundle:Commentaire:createc }
delete_commentaire:
    path:     /delete/{idCommentaire}
    defaults: { _controller: TrocBundle:Commentaire:delete }
update_commentaire:
    path:     /update/{idCommentaire}
    defaults: { _controller: TrocBundle:Commentaire:update }
signaler_commentaire:
    path:     /signaler/{idCommentaire}
    defaults: { _controller: TrocBundle:Commentaire:signaler }
read:
    path:     /read/{id}
    defaults: { _controller: TrocBundle:Annonce:read }
index:
    path:     /index
    defaults: { _controller: TrocBundle:Commentaire:index }

troc_signin:
    path:     /signin
    defaults: { _controller: TrocBundle:Signin:index }

rec_ajout:
    path:     /new
    defaults: { _controller: TrocBundle:Reclamation:new }

feed_ajout:
    path:     /ajoutf
    defaults: { _controller: TrocBundle:Feedback:new }

opinon_ajout:
    path:     /ajouto
    defaults: { _controller: TrocBundle:Opinion:new }
opinion_aff:
    path:     /ajoutof
    defaults: { _controller: TrocBundle:Opinion:show }
signin:
    path:     /signin
    defaults: { _controller: TrocBundle:Connexion:signin }
signup:
    path:     /signup
    defaults: { _controller: TrocBundle:Connexion:signup }
page:
    path:     /single
    defaults: { _controller: TrocBundle:Default:page }

rec_admin:
    path:     /admin
    defaults: { _controller: TrocBundle:Reclamation:Reclamation }