items:
    resource: "@ItemsBundle/Resources/config/routing.yml"
    prefix:   /items
annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /annonce

livraison:
    resource: "@LivraisonBundle/Resources/config/routing.yml"
    prefix:   /livraison

commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"
    prefix:   /commande

troc:
    resource: "@TrocBundle/Resources/config/routing.yml"
    prefix:   /troc

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

troc_opinion:
    resource: "@TrocBundle/Controller/OpinionController.php"
    type:     annotation

troc_feedback:
    resource: "@TrocBundle/Controller/FeedbackController.php"
    type:     annotation

troc_feedback:
    resource: "@TrocBundle/Controller/FeedbackController.php"
    type:     annotation

rec:
    resource: '@TrocBundle/Controller/'
    type: annotation