<?php

namespace Proxies\__CG__\TrocBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commande extends \TrocBundle\Entity\Commande implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'idcommande', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'datecommande', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'montant', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'livraison', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'paye', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'idannonce1', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'idannonce2', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'idclient'];
        }

        return ['__isInitialized__', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'idcommande', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'datecommande', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'montant', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'livraison', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'paye', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'idannonce1', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'idannonce2', '' . "\0" . 'TrocBundle\\Entity\\Commande' . "\0" . 'idclient'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Commande $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdcommande()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdcommande();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcommande', []);

        return parent::getIdcommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecommande($datecommande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecommande', [$datecommande]);

        return parent::setDatecommande($datecommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecommande', []);

        return parent::getDatecommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant($montant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', [$montant]);

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', []);

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivraison($livraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivraison', [$livraison]);

        return parent::setLivraison($livraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivraison', []);

        return parent::getLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaye($paye)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaye', [$paye]);

        return parent::setPaye($paye);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaye', []);

        return parent::getPaye();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdannonce1(\TrocBundle\Entity\Annonce $idannonce1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdannonce1', [$idannonce1]);

        return parent::setIdannonce1($idannonce1);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdannonce1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdannonce1', []);

        return parent::getIdannonce1();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdannonce2(\TrocBundle\Entity\Annonce $idannonce2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdannonce2', [$idannonce2]);

        return parent::setIdannonce2($idannonce2);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdannonce2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdannonce2', []);

        return parent::getIdannonce2();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdclient(\AppBundle\Entity\User $idclient = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdclient', [$idclient]);

        return parent::setIdclient($idclient);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdclient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdclient', []);

        return parent::getIdclient();
    }

}
