<?php

namespace Proxies\__CG__\TrocBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Annonce extends \TrocBundle\Entity\Annonce implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'idAnnonce', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'titreAnnonce', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'prix', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'date', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'typeAnnonce', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'etatAnnonce', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'adresse', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'description', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'iditems', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'idcommande'];
        }

        return ['__isInitialized__', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'idAnnonce', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'titreAnnonce', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'prix', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'date', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'typeAnnonce', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'etatAnnonce', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'adresse', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'description', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'iditems', '' . "\0" . 'TrocBundle\\Entity\\Annonce' . "\0" . 'idcommande'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Annonce $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdAnnonce()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdAnnonce();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAnnonce', []);

        return parent::getIdAnnonce();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreAnnonce($titreAnnonce)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreAnnonce', [$titreAnnonce]);

        return parent::setTitreAnnonce($titreAnnonce);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreAnnonce()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreAnnonce', []);

        return parent::getTitreAnnonce();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeAnnonce($typeAnnonce)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeAnnonce', [$typeAnnonce]);

        return parent::setTypeAnnonce($typeAnnonce);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeAnnonce()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeAnnonce', []);

        return parent::getTypeAnnonce();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatAnnonce($etatAnnonce)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatAnnonce', [$etatAnnonce]);

        return parent::setEtatAnnonce($etatAnnonce);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatAnnonce()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatAnnonce', []);

        return parent::getEtatAnnonce();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setIditems(\TrocBundle\Entity\Items $iditems = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIditems', [$iditems]);

        return parent::setIditems($iditems);
    }

    /**
     * {@inheritDoc}
     */
    public function getIditems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIditems', []);

        return parent::getIditems();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcommande(\TrocBundle\Entity\Commande $idcommande = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcommande', [$idcommande]);

        return parent::setIdcommande($idcommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcommande', []);

        return parent::getIdcommande();
    }

}
