<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMdus7qh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMdus7qh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMdus7qh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMdus7qh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMdus7qh\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Mdus7qh',
    'container.build_id' => '4acff00e',
    'container.build_time' => 1543438452,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMdus7qh');
