<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZooqtoi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZooqtoi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZooqtoi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZooqtoi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZooqtoi\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zooqtoi',
    'container.build_id' => '6889934a',
    'container.build_time' => 1543761217,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZooqtoi');
