<?php

namespace Proxies\__CG__\TrocBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Items extends \TrocBundle\Entity\Items implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TrocBundle\\Entity\\Items' . "\0" . 'iditems', '' . "\0" . 'TrocBundle\\Entity\\Items' . "\0" . 'nomitems', '' . "\0" . 'TrocBundle\\Entity\\Items' . "\0" . 'imgiems', '' . "\0" . 'TrocBundle\\Entity\\Items' . "\0" . 'idsouscat', '' . "\0" . 'TrocBundle\\Entity\\Items' . "\0" . 'idUser'];
        }

        return ['__isInitialized__', '' . "\0" . 'TrocBundle\\Entity\\Items' . "\0" . 'iditems', '' . "\0" . 'TrocBundle\\Entity\\Items' . "\0" . 'nomitems', '' . "\0" . 'TrocBundle\\Entity\\Items' . "\0" . 'imgiems', '' . "\0" . 'TrocBundle\\Entity\\Items' . "\0" . 'idsouscat', '' . "\0" . 'TrocBundle\\Entity\\Items' . "\0" . 'idUser'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Items $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIditems()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIditems();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIditems', []);

        return parent::getIditems();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomitems($nomitems)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomitems', [$nomitems]);

        return parent::setNomitems($nomitems);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomitems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomitems', []);

        return parent::getNomitems();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgiems($imgiems)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgiems', [$imgiems]);

        return parent::setImgiems($imgiems);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgiems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgiems', []);

        return parent::getImgiems();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsouscat(\TrocBundle\Entity\Souscategorie $idsouscat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsouscat', [$idsouscat]);

        return parent::setIdsouscat($idsouscat);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsouscat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsouscat', []);

        return parent::getIdsouscat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUser(\AppBundle\Entity\User $idUser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUser', [$idUser]);

        return parent::setIdUser($idUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUser', []);

        return parent::getIdUser();
    }

}
