<?php

namespace Proxies\__CG__\TrocBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reclamation extends \TrocBundle\Entity\Reclamation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'idRec', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'description', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'date', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'etatReclamation', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'typeReclamation', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'idUser', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'idAnnonce', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'idRuser'];
        }

        return ['__isInitialized__', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'idRec', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'description', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'date', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'etatReclamation', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'typeReclamation', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'idUser', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'idAnnonce', '' . "\0" . 'TrocBundle\\Entity\\Reclamation' . "\0" . 'idRuser'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reclamation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdRec()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdRec();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRec', []);

        return parent::getIdRec();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatReclamation($etatReclamation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatReclamation', [$etatReclamation]);

        return parent::setEtatReclamation($etatReclamation);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatReclamation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatReclamation', []);

        return parent::getEtatReclamation();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeReclamation($typeReclamation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeReclamation', [$typeReclamation]);

        return parent::setTypeReclamation($typeReclamation);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeReclamation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeReclamation', []);

        return parent::getTypeReclamation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUser(\AppBundle\Entity\User $idUser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUser', [$idUser]);

        return parent::setIdUser($idUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUser', []);

        return parent::getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAnnonce(\TrocBundle\Entity\Annonce $idAnnonce = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAnnonce', [$idAnnonce]);

        return parent::setIdAnnonce($idAnnonce);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAnnonce()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAnnonce', []);

        return parent::getIdAnnonce();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRuser(\AppBundle\Entity\User $idRuser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRuser', [$idRuser]);

        return parent::setIdRuser($idRuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRuser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRuser', []);

        return parent::getIdRuser();
    }

}
