<?php

namespace Proxies\__CG__\TrocBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Allocoursier extends \TrocBundle\Entity\Allocoursier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'idalloservice', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'adresseclient', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'adresselivraison', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'description', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'dateenregistrementservice', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'idcoursier', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'idUser'];
        }

        return ['__isInitialized__', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'idalloservice', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'adresseclient', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'adresselivraison', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'description', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'dateenregistrementservice', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'idcoursier', '' . "\0" . 'TrocBundle\\Entity\\Allocoursier' . "\0" . 'idUser'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Allocoursier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdalloservice()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdalloservice();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdalloservice', []);

        return parent::getIdalloservice();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseclient($adresseclient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseclient', [$adresseclient]);

        return parent::setAdresseclient($adresseclient);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseclient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseclient', []);

        return parent::getAdresseclient();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresselivraison($adresselivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresselivraison', [$adresselivraison]);

        return parent::setAdresselivraison($adresselivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresselivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresselivraison', []);

        return parent::getAdresselivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateenregistrementservice($dateenregistrementservice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateenregistrementservice', [$dateenregistrementservice]);

        return parent::setDateenregistrementservice($dateenregistrementservice);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateenregistrementservice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateenregistrementservice', []);

        return parent::getDateenregistrementservice();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcoursier(\AppBundle\Entity\User $idcoursier = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcoursier', [$idcoursier]);

        return parent::setIdcoursier($idcoursier);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcoursier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcoursier', []);

        return parent::getIdcoursier();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUser(\AppBundle\Entity\User $idUser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUser', [$idUser]);

        return parent::setIdUser($idUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUser', []);

        return parent::getIdUser();
    }

}
