<?php

namespace Proxies\__CG__\TrocBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Livraison extends \TrocBundle\Entity\Livraison implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'idlivraison', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'dateenregistrement', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'datelivraison', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'fraislivraison', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'livraisonrecue', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'adresselivraison', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'etatlivraison', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'idcoursier', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'numcommande', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'numal', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'idclient'];
        }

        return ['__isInitialized__', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'idlivraison', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'dateenregistrement', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'datelivraison', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'fraislivraison', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'livraisonrecue', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'adresselivraison', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'etatlivraison', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'idcoursier', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'numcommande', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'numal', '' . "\0" . 'TrocBundle\\Entity\\Livraison' . "\0" . 'idclient'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Livraison $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdlivraison()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdlivraison();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdlivraison', []);

        return parent::getIdlivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateenregistrement($dateenregistrement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateenregistrement', [$dateenregistrement]);

        return parent::setDateenregistrement($dateenregistrement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateenregistrement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateenregistrement', []);

        return parent::getDateenregistrement();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatelivraison($datelivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatelivraison', [$datelivraison]);

        return parent::setDatelivraison($datelivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatelivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatelivraison', []);

        return parent::getDatelivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraislivraison($fraislivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraislivraison', [$fraislivraison]);

        return parent::setFraislivraison($fraislivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraislivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraislivraison', []);

        return parent::getFraislivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivraisonrecue($livraisonrecue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivraisonrecue', [$livraisonrecue]);

        return parent::setLivraisonrecue($livraisonrecue);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivraisonrecue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivraisonrecue', []);

        return parent::getLivraisonrecue();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresselivraison($adresselivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresselivraison', [$adresselivraison]);

        return parent::setAdresselivraison($adresselivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresselivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresselivraison', []);

        return parent::getAdresselivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatlivraison($etatlivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatlivraison', [$etatlivraison]);

        return parent::setEtatlivraison($etatlivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatlivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatlivraison', []);

        return parent::getEtatlivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcoursier(\AppBundle\Entity\User $idcoursier = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcoursier', [$idcoursier]);

        return parent::setIdcoursier($idcoursier);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcoursier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcoursier', []);

        return parent::getIdcoursier();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumcommande(\TrocBundle\Entity\Commande $numcommande = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumcommande', [$numcommande]);

        return parent::setNumcommande($numcommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumcommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumcommande', []);

        return parent::getNumcommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumal(\TrocBundle\Entity\Allocoursier $numal = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumal', [$numal]);

        return parent::setNumal($numal);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumal', []);

        return parent::getNumal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdclient(\AppBundle\Entity\User $idclient = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdclient', [$idclient]);

        return parent::setIdclient($idclient);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdclient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdclient', []);

        return parent::getIdclient();
    }

}
