commande_homepage:
    path:     /
    defaults: { _controller: CommandeBundle:Default:index }

read_commande:
    path:     /read
    defaults: { _controller: CommandeBundle:Commande:read }

create_commande:
    path:     /create
    defaults: { _controller: CommandeBundle:Commande:create }

update_commande:
    path:     /update/{id}
    defaults: { _controller: CommandeBundle:Commande:update }

delete_commande:
    path:     /delete/{id}
    defaults: { _controller: CommandeBundle:Commande:delete }

affiche_annonce:
    path:     /affichannonce/{id}
    defaults: { _controller: CommandeBundle:Commande:affichAnnonce }

supprimer_pannier:
    path:     /deletefromcart/{id}
    defaults: { _controller: CommandeBundle:Commande:deleteFromCart }

ajouter_pannier:
    path:     /addtocart/{id}
    defaults: { _controller: CommandeBundle:Commande:addToCart }

troc_annonce:
    path:     /troquer/{id}
    defaults: { _controller: CommandeBundle:Commande:troquer }

valider_troc_annonce:
    path:     /validertroc/{idA1,idA2}
    defaults: { _controller: CommandeBundle:Commande:validerTroc }

test:
    path:     /test
    defaults: { _controller: CommandeBundle:Commande:test }

imprimer_facture:
    path:     /print/{id}
    defaults: { _controller: CommandeBundle:Commande:print }


stats:
    path:     /stats
    defaults: { _controller: CommandeBundle:Commande:stats }

find_all_mobile:
    path:     /findall
    defaults: { _controller: CommandeBundle:Commande:all }

find_mobile:
    path:     /find/{id}
    defaults: { _controller: CommandeBundle:Commande:find }

new_mobile:
    path:     /new
    defaults: { _controller: CommandeBundle:Commande:new }

add_cart_mobile:
    path:     /addCart/{id}
    defaults: { _controller: CommandeBundle:Commande:addCartMobile }

remove_cart_mobile:
    path:     /removeCart/{id}
    defaults: { _controller: CommandeBundle:Commande:removeCartMobile }

remove_mobile:
    path:     /removeMobile/{id}
    defaults: { _controller: CommandeBundle:Commande:removeMobile }

get_order_mobile:
    path:     /getOrder/{id}
    defaults: { _controller: CommandeBundle:Commande:getOrder }

update_mobile:
    path:     /updateMobile
    defaults: { _controller: CommandeBundle:Commande:updateMobile }

get_annonces_mobile:
    path:     /getAnnonces
    defaults: { _controller: CommandeBundle:Commande:getAnnoncesMobile }

valider_troc_mobile:
    path:     /validerTroc
    defaults: { _controller: CommandeBundle:Commande:validerTrocMobile }
