<?php

namespace TrocBundle\Repository;

/**
 * AllocoursierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllocoursierRepository extends \Doctrine\ORM\EntityRepository
{

}
