<?php

namespace TrocBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindall($id)
    {
        $query=$this->getEntityManager()->createQuery("select a from TrocBundle:Annonce a where a.idAnnonce=$id");
        return $query->getResult();
    }

    public function orderDate()
    {
        $query=$this->getEntityManager()->createQuery("select a from TrocBundle:Annonce a ORDER BY a.date DESC ");
        return $query->getResult();
    }

    public function topView()
    {
        $query=$this->getEntityManager()->createQuery("select a from TrocBundle:Annonce a WHERE a.view=
            (SELECT MAX(B.view) as nbre FROM TrocBundle:Annonce B )");
        return $query->getResult();
    }

    public function search($word)
    {
        $query=$this->getEntityManager()->createQuery("select a from TrocBundle:Annonce a WHERE a.titreAnnonce like :keyword");
        $query->setParameter(':keyword', '%'.$word.'%');
        return $query->getResult();
    }
}
