<?php

namespace TrocBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastCommande()
    {
        $query=$this->getEntityManager()->createQuery("select c from TrocBundle:Commande c ORDER by ID DESC LIMIT 1");

        return $query->getResult();
    }


}
