<?php

namespace TrocBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastCommande()
    {
        $query=$this->getEntityManager()->createQuery("select c from TrocBundle:Commande c where c.idclient = 1 ORDER by c.idcommande DESC ");
        return $query->getResult();
    }

    public function findAllExchange()
    {
        $query=$this->getEntityManager()->createQuery("select c from TrocBundle:Commande c where c.idannonce1 != 'NULL'  ");
        return $query->getResult();
    }

    public function findAllSell()
    {
        $query=$this->getEntityManager()->createQuery("select c from TrocBundle:Commande c where c.montant != 0  ");
        return $query->getResult();
    }

    public function affectercoursier()
    {
        $query = $this->getEntityManager()->createQuery(" select  COUNT(l.idlivraison) as x ,u.id as id from  AppBundle:User u ,TrocBundle:Livraison l where l.idcoursier=u.id and l.etatlivraison=0  GROUP BY l.idcoursier ORDER by x ASC  ") ;
        return $query->getResult();
    }
}
