<?php

namespace TrocBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByAnnonce($id)
    {
        $query = $this->getEntityManager()->createQuery("select c from TrocBundle:Commentaire c where c.idAnnonce=$id");

        return $query->getResult();
    }

    public function  TopCommented()
    {
        $query = $this->getEntityManager()
            ->createQuery("select  COUNT c.idCommentaire AS nbre_commentaire 
          from TrocBundle:Commentaire as c GROUP BY c.idAnnonce|PartialObjectExpression  ORDER BY nbre_commentaire DESC ");

        $nbr=$query->getResult();

        $query = $this->getEntityManager()
            ->createQuery("select  c.idAnnonce from TrocBundle:Commentaire as c where COUNT c.idAnnonce.idCommentaire=$nbr");
        $annonce=$query->getResult();

        return $query->getResult();
    }


}
