<?php

namespace TrocBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByAnnonce($id)
    {
        $query = $this->getEntityManager()->createQuery("select c from TrocBundle:Commentaire c where c.idAnnonce=$id");

        return $query->getResult();
    }


}
