<?php

namespace TrocBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByAnnonce($id)
    {
        $query = $this->getEntityManager()->createQuery("select c from TrocBundle:Commentaire c where c.idAnnonce=$id");

        return $query->getResult();
    }
    public function countComment()
    {
        $query = $this->getEntityManager()->createQuery(" select  COUNT(c) AS nbre_commentaire  from TrocBundle:Commentaire c GROUP BY c.idAnnonce ORDER BY nbre_commentaire DESC ");

        return $query->getResult();
    }
    public function idComment()
    {
       // $query = $this->getEntityManager()->createQuery(" select c.idannonce from TrocBundle:Commentaire c  ");
      //  return $query->getResult();
    }


}
