<?php

namespace TrocBundle\Repository;


/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFeed($id)
    {
        $query=$this->getEntityManager()
            ->createQuery("select f from TrocBundle:Feedback f JOIN TrocBundle:Annonce a where f.idAnnonce=$id");

        return $query->getSingleResult();
    }
    public function addFeed($idA)
    {
        $query=$this->getEntityManager()
            ->createQuery("select f from TrocBundle:Feedback f JOIN TrocBundle:Annonce a where a.idAnnonce=$idA");

        return $query->getSingleResult();
    }
    public function findFeedback($user,$a)
    {
        $query=$this->getEntityManager()
            ->createQuery("select f from TrocBundle:Feedback f JOIN TrocBundle:Annonce a 
      JOIN AppBundle:User u where f.idAnnonce=a and f.idUser=u and f.idAnnonce=$a and f.idUser.id=$user");

        return $query->getResult();
    }
    public function LikeDislike($a)
    {
        $query=$this->getEntityManager()
            ->createQuery("select SUM (f.likeFeed) as nbl ,SUM (f.dislike) as nbd from TrocBundle:Feedback f 
          JOIN TrocBundle:Annonce a where f.idAnnonce=a and f.idAnnonce=$a");

        return $query->getResult();
    }
}
