<?php

namespace TrocBundle\Repository;

/**
 * OpinionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpinionRepository extends \Doctrine\ORM\EntityRepository
{

    public function MoyNoteOpinion()
    {
        $query=$this->getEntityManager()
            ->createQuery("select SUM(o.note),COUNT(o.note)from TrocBundle:Opinion as o ");
        return $query->getSingleResult();

    }
}
