<?php

namespace TrocBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function count($id)
    {
        $query=$this->getEntityManager()->createQuery("select COUNT (r.idRec),r from TrocBundle:Reclamation r JOIN AppBundle:User u
          GROUP by (r.idRuser)");

        return $query->getSingleResult();
    }
}
