<?php

namespace TrocBundle\Repository;

/**
 * SignalerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalerRepository extends \Doctrine\ORM\EntityRepository
{
    public function countReport()
    {
        $query=$this->getEntityManager()->createQuery("select count(s.idCommentaire) as nbr,s as obj from TrocBundle:Signaler s 
  group by s.idCommentaire");

        return $query->getResult();
    }
    public function counnntReport()
    {
        $query=$this->getEntityManager()->createQuery("select count(s.idCommentaire)  as nbr,s.idCommentaire,c.commentaire , s.idUser , from TrocBundle:Signaler s
  JOIN TrocBundle:Commentaire c where s.idCommentaire=c.idCommentaire  ");

        return $query->getResult();
    }

}
